name: Documentation Update

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  notify-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Get commit info
        id: commit
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          COMMIT_TIMESTAMP=$(git log -1 --pretty=%cI)
          FIRST_WORD=$(echo "$COMMIT_MSG" | cut -d" " -f1 | sed 's/://')
          
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "timestamp=$COMMIT_TIMESTAMP" >> $GITHUB_OUTPUT
          echo "first_word=$FIRST_WORD" >> $GITHUB_OUTPUT
      
      - name: Send webhook
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: sha256=${{ secrets.WEBHOOK_SECRET }}" \
            -d "{
              \"ref\": \"refs/heads/${{ github.ref_name }}\",
              \"commits\": [
                {
                  \"id\": \"${{ steps.commit.outputs.hash }}\",
                  \"message\": \"${{ steps.commit.outputs.message }}\",
                  \"timestamp\": \"${{ steps.commit.outputs.timestamp }}\",
                  \"author\": {
                    \"name\": \"${{ steps.commit.outputs.author }}\",
                    \"email\": \"${{ github.actor }}@users.noreply.github.com\"
                  },
                  \"url\": \"${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.commit.outputs.hash }}\",
                  \"added\": [],
                  \"modified\": [],
                  \"removed\": []
                }
              ],
              \"repository\": {
                \"name\": \"${{ github.event.repository.name }}\",
                \"full_name\": \"${{ github.repository }}\",
                \"html_url\": \"${{ github.event.repository.html_url }}\",
                \"clone_url\": \"${{ github.event.repository.clone_url }}\"
              },
              \"pusher\": {
                \"name\": \"${{ github.actor }}\"
              },
              \"sender\": {
                \"login\": \"${{ github.actor }}\"
              }
            }"
